Dictionary
scopchik/travel_line_practice pull request #2
Opened 2024-07-03 10:31 UTC by scopchik

2024-07-04 11:38 UTC, Nafanyan requested changes
Сделал круто, лаконично, понятно.   

Давай со следующего ПР уходить с top-level statements, если будут вопросы напиши

2024-07-04 11:38 UTC, Nafanyan commented on Dictionary/Dictionary/Program.cs
> +const string filePath = "dictionary.txt";
вопрос на засыпку, где создается этот файл?)

2024-07-04 11:38 UTC, Nafanyan commented on Dictionary/Dictionary/Program.cs
> +            var parts = line.Split( ':' );
var'ы лучше использовать только когда из правой части понятно что за тип данных будет использоваться, например
var person = new Person();
var number = 12;
var name = "Kkkken"

2024-07-04 11:38 UTC, Nafanyan commented on Dictionary/Dictionary/Program.cs
> +                dictionary[ parts[ 0 ].Trim() ] = parts[ 1 ].Trim();
dictionary, каеф

2024-07-04 11:38 UTC, Nafanyan commented on Dictionary/Dictionary/Program.cs
> +        Console.WriteLine( "Слово уже существует в словаре." );
Было бы круто если бы программа сказала мне что такое слово уже существует на этапе, когда я ввел слово на русском. А то получается что я попаду в заблуждение вводя его перевод)

2024-07-04 11:38 UTC, Nafanyan commented on Dictionary/Dictionary/Program.cs
> +        Console.WriteLine( "Слово уже существует в словаре." );
И типа "Такое слово уже существует в словаре, его перевод:..."

2024-07-04 11:38 UTC, Nafanyan commented on Dictionary/Dictionary/Program.cs
> +            SaveDictionaryToFile();
да, лучше сохранять изменения перед выходом из программы чтобы не тратить ресурсы на периодическую работу с файлом, любая работа с ОС это дорого

2024-07-04 11:38 UTC, Nafanyan commented on Dictionary/Dictionary/Program.cs
> +    string choice = Console.ReadLine();
choice  => выбор?

Может что-то типа command?

2024-07-04 11:38 UTC, Nafanyan commented on Dictionary/Dictionary/Program.cs
> +            foreach ( var entry in dictionary )
var'ы лучше в таких случая не использовать)

2024-07-04 16:01 UTC, scopchik commented on Dictionary/Dictionary/Program.cs
> +const string filePath = "dictionary.txt";
Dictionary\bin\Debug\net8.0

2024-07-05 11:45 UTC, Nafanyan approved these changes
Можешь squash'ить и мержить)

Если будут вопросы по squash'у смотри коммент 1го ПРа, либо пиши

2024-07-05 11:45 UTC, Nafanyan commented on Dictionary/Dictionary/Program.cs
> +    if ( !dictionary.ContainsKey( russianWord ) )
Есть один подход для упрощения конструкций условий. Если одно условие значительно толще другого, то то, где меньше кода лучше поместить выше. У тебя это сделано в строках 62-74, можешь поправить, если хочешь)

2024-07-05 12:31 UTC, merged