Sql commit
scopchik/travel_line_practice pull request #4
Opened 2024-07-11 19:45 UTC by scopchik

2024-07-16 19:27 UTC, Nafanyan requested changes
Не торопись, лучше читай ТЗ и обдумывай свои решения

2024-07-16 19:27 UTC, Nafanyan commented on SQL.sql
> +		price_per_night INT NOT NULL,
цену в int точно не храним за это сразу в бан))))))))

2024-07-16 19:27 UTC, Nafanyan commented on SQL.sql
> +		availability NVARCHAR(50) NOT NULL,
у доступности может быть только два значения, доступно и недоступно, представь как разрастется БД если ты будешь хранить для каждой записи строку длиной в 50 байт (по моему). Причем насколько я помню даже если запись будет занимать меньше места, то память будет выделяться фиксированная, поправь если неправ. Лучше использовать bit

2024-07-16 19:27 UTC, Nafanyan commented on SQL.sql
> +		first_name NVARCHAR(100) NOT NULL,
Да ну, как будто слишком длинное имя, фамилия, мыло)))

2024-07-16 19:27 UTC, Nafanyan commented on SQL.sql
> +SELECT * FROM dbo.Rooms
"Найдите все доступные номера для бронирования сегодня.", а этот скрипт нашел мне свободные номера за всё время)

2024-07-16 19:27 UTC, Nafanyan commented on SQL.sql
> +/*Find all bookings for a specific customer (by name or email)*/
хех, подписывай уж тогда все задания, и лучше на русском, и лучше через "--"

2024-07-16 19:27 UTC, Nafanyan commented on SQL.sql
> +ON B.customer_id = C.customer_id
лучше чтобы on было в той же строке где join

2024-07-16 19:27 UTC, Nafanyan commented on SQL.sql
> +SELECT * FROM dbo.Bookings B
ты мне вывел инфу из таблицы Rooms, хотя мне нужна только информация о бронировании, используй B.* после селекта

2024-07-16 19:27 UTC, Nafanyan commented on SQL.sql
> +/*Find all rooms that are not booked for a specific date*/
"Найдите все номера, которые не забронированы на определенную дату." а проверку на доступность делать не будешь?)

2024-07-20 13:20 UTC, Imran-imtiaz48 reviewed
The provided SQL scripts include modifications to the database schema and data, specifically focusing on the `Rooms` and `Customers` tables. Additionally, there are several queries aimed at retrieving data based on certain conditions.

#### Review Points

1. **Schema Changes**:
   - Changes in the `Rooms` table schema:
     - `price_per_night` column type changed from `INT` to `FLOAT`.
     - `availability` column type changed from `NVARCHAR(50)` to `BIT`.
   - Changes in the `Customers` table schema:
     - Length of `first_name`, `last_name`, and `email` columns reduced.
   - These changes are beneficial for improving data integrity and performance.

2. **Data Insertions**:
   - Insertions into the `Rooms` table are updated to reflect the new data types.
   - `availability` is now represented by `true` and `false` instead of `Free` and `Busy`.

3. **Queries**:
   - Several queries are included to select data from the tables based on different conditions.

#### Suggestions for Improvement

1. **Schema Changes**:
   - Ensure that the data migration script handles the transformation of existing data, especially for the `availability` column.

2. **Data Insertions**:
   - Verify that the boolean values (`true`, `false`) are correctly interpreted by the SQL engine.
   - It might be clearer to use `1` and `0` for the `BIT` type depending on the SQL engine's requirements.

3. **Queries**:
   - Ensure that the indexes are optimized for the queries provided, especially for frequently run queries.
   - The query comments should follow a consistent style for better readability.

#### Detailed Code Review

```sql
-- Changes in Rooms table schema
CREATE TABLE dbo.Rooms (
    room_id INT IDENTITY(1, 1) NOT NULL,
    room_number INT NOT NULL,
    room_type NVARCHAR(50) NOT NULL,
    price_per_night FLOAT NOT NULL, -- Changed from INT to FLOAT
    availability BIT NOT NULL, -- Changed from NVARCHAR(50) to BIT
    CONSTRAINT PK_Rooms_room_id PRIMARY KEY (room_id)
);

-- Changes in Customers table schema
CREATE TABLE dbo.Customers (
    customer_id INT IDENTITY(1, 1) NOT NULL,
    first_name NVARCHAR(20) NOT NULL, -- Reduced length
    last_name NVARCHAR(30) NOT NULL, -- Reduced length
    email NVARCHAR(30) NOT NULL, -- Reduced length
    phone_number NVARCHAR(30) NOT NULL,
    CONSTRAINT PK_Customers_customer_id PRIMARY KEY (customer_id)
);

-- Insertions into Rooms table
INSERT INTO dbo.Rooms
VALUES
    (1, 'Single', 2500, 'true'),
    (15, 'Single', 2500, 'false'),
    (20, 'Double', 3500, 'false'),
    (30, 'Single', 2500, 'false'),
    (40, 'Triple', 5500, 'true'),
    (50, 'Triple', 5500, 'false');

-- Data insertion consistency check
-- Ensure all columns match the defined schema in terms of data type and constraints

-- Queries

-- Select all rooms where availability is true
SELECT * FROM dbo.Rooms
WHERE availability = 'true'; -- Consider using 1 or true depending on SQL dialect

-- Select all customers with a last name starting with 'S'
SELECT * FROM dbo.Customers
WHERE last_name LIKE 'S%';

-- Find all bookings for a specific customer by name or email
SELECT * FROM dbo.Bookings B
JOIN dbo.Customers C
ON B.customer_id = C.customer_id
WHERE C.first_name = 'Anatoly';

-- Find all bookings for a specific room
SELECT * FROM dbo.Bookings B
JOIN dbo.Rooms R
ON B.room_id = R.room_id
WHERE R.room_number = 145;

-- Find all rooms that are not booked for a specific date
SELECT * FROM dbo.Rooms R
JOIN dbo.Bookings B
ON R.room_id = B.room_id
WHERE ('2024-07-15' NOT BETWEEN B.check_in_date AND B.check_out_date);
```

#### Additional Considerations

1. **Error Handling**:
   - Consider adding error handling mechanisms, especially during data insertions and updates.

2. **Documentation**:
   - Add detailed comments to explain the purpose of each query and any assumptions made.

3. **Performance Testing**:
   - Conduct performance testing to ensure that the changes do not negatively impact the database performance.

By addressing these suggestions, the SQL scripts will be more robust, maintainable, and optimized for performance.

2024-08-09 05:47 UTC, Nafanyan requested changes
поправь один скрипт и мелкие замечания и апрувну

2024-08-09 05:47 UTC, Nafanyan commented on FindHotels.sql
> +SELECT * FROM dbo.Rooms
"Найдите все доступные номера для бронирования сегодня.", это всё ещё просто свободные комнаты, а нужны номера именно на сегодняшнюю дату.

**p.s.** Попробуй заиспользовать информацию из таблицы Bookings. При таком запросе возможна следующая ситуация:
Я смотрю информацию по номеру в 10:00, номер свободен, я заселяю туда людей. Наступает 14:00, приезжают люди, которые бронировали этот номер, а я уже туда поселил других, не красиво.

2024-08-09 05:47 UTC, Nafanyan commented on FindHotels.sql
> +B.room_id = R.room_id
придирка, после ON не переноси на другую строку

2024-08-09 05:47 UTC, Nafanyan commented on FindHotels.sql
> +R.room_id = B.room_id
придирка, после ON не переноси на другую строку

2024-08-09 05:47 UTC, Nafanyan commented on FindHotels.sql
> +WHERE (('2024-07-15' < B.check_in_date) OR (B.check_out_date > '2024-07-15')) and availability = 'true';
WHERE (('2024-07-15' < B.check_in_date) OR (B.check_out_date > '2024-07-15')) **AND** availability = 'true';

2024-08-19 05:47 UTC, Nafanyan requested changes

2024-08-19 05:47 UTC, Nafanyan commented on FindHotels.sql
> +	where availability = 'true' and check_in_date <= '2024-07-22');
Для корректного выполнения этого скрипта каждый день мне нужно будет его переписывать, не очень удобно, я бы сказал вообще не удобно))

Ладно не буду тебя мучать, посмотри на это и сделай выводы:

```sql
SELECT * FROM Rooms
WHERE room_id NOT IN (
    SELECT room_id FROM Bookings
    WHERE GETDATE() NOT BETWEEN check_in_date AND check_out_date 
) AND availability = 1;
```

2024-09-16 16:21 UTC, merged